### ISSUE TITLE
screwdriver do not 

### ISSUE THREAD

**Issue by yoshwata** [yoshwata/urfaveTest#2]
**What happened**:
Screwdriver loads a screwdriver.yaml like below, then starts build.
```
jobs:
    main:
        image: centos
        requires: [~pr, ~commit]
        steps:
          - echo01: echo "foo"
          - exit01: exit 0
          - echo02: echo "bar"
```

Pileline stop with error on step `echo02`.

**What you expected to happen**:
Screwdriver does not stop the pipeline. `exit 0` is frequently use case as shell programming.
